# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2000240b35cfc313d8ab711bb8bbafa9229654a0420dd6485eac8d03369f850e766ab553e37627a517be46fbe6393a27ca7765a56938528845c91fcf01974367

test:
  secret_key_base: 378709a33f1ef5789436f4b8ed869b4b0721bfb5db709d2655593c9d7c9aef602c1688f44906fa6e2804d75603114377d7d0ee492c71e47c61adbc27201c62e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
